templates/master-template.html
added role="presentation" to all tables
=> accessibility update

templates/master-template.html
Formatted HTML to improve readability
=> Formatted HTML

snippets/crm_service_message_header
added attributes to notification image to stabilise rendering
added min-width to tables for gmail app
=> stabilized image rendering and gmail app fix

templates/master-template.html
=> Meme content blocks

snippets/crm_intro
Simplifying and removing breaks.
=> Simplification of intro snippet

snippets/crm_columnists.html
Hey @melanierogan , can you just take a quick glance at this code and approve if it looks good.
Thanks
=> added stable crm_columnists module

templates/crm-master-template.html
removed redundant classes and some styling. Was looking at this issues https://github.com/Financial-Times/crm-meme-templates/issues/32 and while i could not come up with a fix for this, did a bit of tidying while I was there.
Litmus test here: https://litmus.com/builder/15cc25f
=> header code improvements

snippets/crm_topics_2x2_api.html
Updated loops in api block and redid the block to have padding split between tds inside and outside the loop. Pending review this is ready for gmail fix.
=> Update loops in api block

snippets/add_to_my_ft_recommendations.html
added new snippet to recommend new myft topics to follow
=> Added add to myft snippet

README.md
@melanierogan can you think of any other initial things that should go in here? I know there will be things I have missed off but I can't think
=> added initial coding conventions

snippets/crm_banner_fullwidth.html, snippets/crm_hero_with_mobile.html, snippets/crm_intro.html, snippets/crm_topics_2x2.html, snippets/crm_topics_2x2_api.html, snippets/crm_topics_2x2_highlighted.html, templates/crm-master-template.html
Quite a lot to look at here.
I have looked at:
Hero
Banner
2x2
2x2 feature
2x2 api
It is working on Aislinn’s pc
Litmus test can be found here:
https://litmus.com/builder/7a32a9c
Email linke here:
http://email.permalink.ft.com/emails/eyJlbWFpbCI6ImYxZDIxYzQxMGM4NmI2Njc1ZjY0MjIyNWRjNzhkYTUwZTMwZGYyNjM5YzVlIiwidHJhbnNhY3Rpb25JZCI6IjkwY2RlYTllLTk0YTEtNDgyZC1hZTc2LWIyMDJhMjllMjZhYyJ9
=> Gmail fix two column

snippets/Hero/crm_hero_feature_article_intro_badge.html, snippets/Hero/crm_hero_intro_large_feature_article.html, snippets/Hero/crm_hero_intro_large_feature_article_badge.html, snippets/Hero/crm_hero_large_feature_article_intro.html, snippets/Hero/crm_hero_large_feature_article_intro_badge.html
=> Hero area implementation

snippets/Hero/crm_hero_feature_article_intro_badge.html, snippets/Hero/crm_hero_intro_feature_article_badge.html, snippets/Hero/crm_hero_intro_large_feature_article_badge.html, snippets/Hero/crm_hero_large_feature_article_intro_badge.html
litmus test here:
https://litmus.com/builder/61ba0a5
=> updated hero snippets to fix badge bug

templates/crm-master-template_service.html
- added header to template (so service header can be depreciated)
-  wrapped sections in tables
- added padding to main content area
=> Service template update

snippets/crm_newsletter_promo_banner.html
added snippet for newsletter promo
=> Newsletter snippet

templates/crm-master-template.html
Added social and app footer to master template.
Litmus test is here:
https://litmus.com/builder/69b02df
=> Social app footer

snippets/b2c_marketing_features_list.html
New snippet created for the retention team to be used for more detailed descriptions of features.
Built using divs
Litmus test:
https://litmus.com/builder/20e9937
=> Features list snippet

templates/FT-transact-template.html, templates/b2c_marketing_template.html, templates/crm-newsletter-template.html
Not a big thing but this will remove a redirect for fonts.
=> Update legacy build service URLs

GDPR footers/Footer snippets/top-stories-&-features.html
Fixing typo from you preferences to yours
=> Fixing typo

GDPR footers/Footer snippets/top-stories-&-features.html
'you contact preferences' to your contact preferences
=> Typo in the copy
